//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.TranslatorsInBooks = new HashSet<TranslatorsInBook>();
            this.Books = new HashSet<Book>();
            this.ViewStats = new HashSet<ViewStat>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Incomes = new HashSet<Income>();
            this.Flags = new HashSet<Flag>();
        }
    
        public System.Guid AuthorId { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string OfficialUrl { get; set; }
        public System.DateTime PhotoUpdated { get; set; }
        public bool FromWiki { get; set; }
        public string Name { get; set; }
        public string Biography { get; set; }
        public string SourceUrl { get; set; }
        public string NameFromWiki { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<TranslatorsInBook> TranslatorsInBooks { get; set; }
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<ViewStat> ViewStats { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual ICollection<Flag> Flags { get; set; }
    }
}
