//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookContents = new HashSet<BookContent>();
            this.BookInSeries = new HashSet<BookInSerie>();
            this.BookMedias = new HashSet<BookMedia>();
            this.BookRelations = new HashSet<BookRelation>();
            this.BookRelationsRef = new HashSet<BookRelation>();
            this.Comments = new HashSet<Comment>();
            this.ExternalUris = new HashSet<ExternalUri>();
            this.Ratings = new HashSet<Rating>();
            this.Reviews = new HashSet<Review>();
            this.TranslatorsInBooks = new HashSet<TranslatorsInBook>();
            this.UserStats = new HashSet<UserStat>();
            this.Authors = new HashSet<Author>();
            this.Genres = new HashSet<Genre>();
            this.ViewStats = new HashSet<ViewStat>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Incomes = new HashSet<Income>();
            this.Flags = new HashSet<Flag>();
            this.Citations = new HashSet<Citation>();
            this.Downloads = new HashSet<Download>();
        }
    
        public System.Guid BookId { get; set; }
        public string Name { get; set; }
        public Nullable<int> PagesCount { get; set; }
        public string Publisher { get; set; }
        public byte[] Cover { get; set; }
        public System.DateTime CoverUpdated { get; set; }
        public string ClearName { get; set; }
        public Nullable<int> Written { get; set; }
        public int IntBookId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> FromGoogleBooks { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public UserDownloadAccessEnum UserDownloadAccess { get; set; }
    
        public virtual ICollection<BookContent> BookContents { get; set; }
        public virtual ICollection<BookInSerie> BookInSeries { get; set; }
        public virtual ICollection<BookMedia> BookMedias { get; set; }
        public virtual ICollection<BookRelation> BookRelations { get; set; }
        public virtual ICollection<BookRelation> BookRelationsRef { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<ExternalUri> ExternalUris { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<TranslatorsInBook> TranslatorsInBooks { get; set; }
        public virtual ICollection<UserStat> UserStats { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<ViewStat> ViewStats { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Flag> Flags { get; set; }
        public virtual ICollection<Citation> Citations { get; set; }
        public virtual ICollection<Download> Downloads { get; set; }
    }
}
