//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRelation
    {
        public System.Guid BookId { get; set; }
        public System.Guid RelatedBookId { get; set; }
        public double Score { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public bool IsRelatedByGenre { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Book BookRef { get; set; }
        public virtual User User { get; set; }
    }
}
