//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookContent
    {
        public System.Guid BookContentId { get; set; }
        public byte[] Content { get; set; }
        public string ContentType { get; set; }
        public bool IsOwnContent { get; set; }
        public string SourceFileName { get; set; }
        public Nullable<int> Size { get; set; }
        public string InternalBookId { get; set; }
        public System.Guid BookId { get; set; }
        public byte[] Source { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
