//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public System.Guid ComplainId { get; set; }
        public System.DateTime Created { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> CommentId { get; set; }
        public short State { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
