//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public System.Guid DownloadId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid BookId { get; set; }
        public System.DateTime Created { get; set; }
        public int DownloadType { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
