//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalResource
    {
        public ExternalResource()
        {
            this.ExternalUris = new HashSet<ExternalUri>();
        }
    
        public System.Guid ExternalResourceId { get; set; }
        public byte[] ResourceIcon { get; set; }
        public string ResourceName { get; set; }
    
        public virtual ICollection<ExternalUri> ExternalUris { get; set; }
    }
}
