//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flag
    {
        public System.Guid FlagId { get; set; }
        public Nullable<System.Guid> BookId { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
        public Nullable<System.Guid> SerieId { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
        public virtual Serie Series { get; set; }
    }
}
