//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.ViewStats = new HashSet<ViewStat>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public System.Guid ReviewId { get; set; }
        public System.Guid BookId { get; set; }
        public System.Guid UserId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsPublished { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ViewStat> ViewStats { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
