//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public Serie()
        {
            this.BookInSeries = new HashSet<BookInSerie>();
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.ViewStats = new HashSet<ViewStat>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Incomes = new HashSet<Income>();
            this.Flags = new HashSet<Flag>();
        }
    
        public System.Guid SerieId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<BookInSerie> BookInSeries { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<ViewStat> ViewStats { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual ICollection<Flag> Flags { get; set; }
    }
}
