//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    
    public enum UserStatStateEnum : short
    {
        None = 0,
        WantsToRead = 1,
        Read = 2,
        IsReading = 3
    }
}
