//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Authors = new HashSet<Author>();
            this.BookRelations = new HashSet<BookRelation>();
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.Reviews = new HashSet<Review>();
            this.UserAuthProfiles = new HashSet<UserAuthProfile>();
            this.UserStats = new HashSet<UserStat>();
            this.UserRoles = new HashSet<UserRole>();
            this.ViewStats = new HashSet<ViewStat>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Incomes = new HashSet<Income>();
            this.Books = new HashSet<Book>();
            this.Complains = new HashSet<Complain>();
            this.OpdsLinks = new HashSet<OpdsLink>();
            this.Incomes1 = new HashSet<Income>();
            this.Devices = new HashSet<Device>();
            this.Citations = new HashSet<Citation>();
            this.Downloads = new HashSet<Download>();
        }
    
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Cellular { get; set; }
        public string Email { get; set; }
        public byte[] Avatar { get; set; }
        public System.DateTime AvatarUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastAccessed { get; set; }
        public bool IsLocked { get; set; }
        public bool IsSubscriber { get; set; }
        public string Comment { get; set; }
        public int IntUserId { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<BookRelation> BookRelations { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<UserAuthProfile> UserAuthProfiles { get; set; }
        public virtual ICollection<UserStat> UserStats { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<ViewStat> ViewStats { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual ICollection<OpdsLink> OpdsLinks { get; set; }
        public virtual ICollection<Income> Incomes1 { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual ICollection<Citation> Citations { get; set; }
        public virtual ICollection<Download> Downloads { get; set; }
    }
}
