//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knigoskop.Site.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Knigoskop.Site.Localization.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О сервисе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О проекте.
        /// </summary>
        public static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;«{0}» - это некоммерческий проект, посвященный литературе. В нем собраны данные о громадном множестве книг и авторов.&lt;/p&gt;
        ///
        ///&lt;p&gt;Цель проекта - объединить любителей литературы, предоставив комфортную среду для поиска и обсуждения книг. Дать возможность делиться мыслями и получать информацию о новинках. &lt;/p&gt;
        ///
        ///&lt;p&gt;Для наших пользователей мы реализовали удобный поиск в нашем каталоге, систему рекомендаций, персональный каталог.&lt;/p&gt;
        ///
        ///&lt;p&gt;Мы не собираемся останавливаться на достигнутом – надеемся, что сайт,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutProjectText {
            get {
                return ResourceManager.GetString("AboutProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск среди.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddAuthorTitle.
        /// </summary>
        public static string AddAuthorTitle {
            get {
                return ResourceManager.GetString("AddAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить книгу.
        /// </summary>
        public static string AddBook {
            get {
                return ResourceManager.GetString("AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая книга.
        /// </summary>
        public static string AddBookTitle {
            get {
                return ResourceManager.GetString("AddBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый автор.
        /// </summary>
        public static string AddNewAuthor {
            get {
                return ResourceManager.GetString("AddNewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указать жанр.
        /// </summary>
        public static string AddNewGenre {
            get {
                return ResourceManager.GetString("AddNewGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая серия.
        /// </summary>
        public static string AddNewSerie {
            get {
                return ResourceManager.GetString("AddNewSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая рецензия.
        /// </summary>
        public static string AddReviewTitle {
            get {
                return ResourceManager.GetString("AddReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключите социальные сети.
        /// </summary>
        public static string AddSocialNetworks {
            get {
                return ResourceManager.GetString("AddSocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а также многое другое....
        /// </summary>
        public static string AndMuchMore {
            get {
                return ResourceManager.GetString("AndMuchMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннотация.
        /// </summary>
        public static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизоваться через.
        /// </summary>
        public static string AuthorizeVia {
            get {
                return ResourceManager.GetString("AuthorizeVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string AuthorNominative {
            get {
                return ResourceManager.GetString("AuthorNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторов.
        /// </summary>
        public static string AuthorPlural {
            get {
                return ResourceManager.GetString("AuthorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автора.
        /// </summary>
        public static string AuthorSingular {
            get {
                return ResourceManager.GetString("AuthorSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аватар.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться на главную.
        /// </summary>
        public static string BackToMain {
            get {
                return ResourceManager.GetString("BackToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биография.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искать в библиотеках.
        /// </summary>
        public static string BookInLibs {
            get {
                return ResourceManager.GetString("BookInLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название книги.
        /// </summary>
        public static string BookName {
            get {
                return ResourceManager.GetString("BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга.
        /// </summary>
        public static string BookNominative {
            get {
                return ResourceManager.GetString("BookNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книги автора.
        /// </summary>
        public static string BookOfAuthor {
            get {
                return ResourceManager.GetString("BookOfAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книг.
        /// </summary>
        public static string BookPlural {
            get {
                return ResourceManager.GetString("BookPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книги.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавил(а) книг.
        /// </summary>
        public static string BooksCount {
            get {
                return ResourceManager.GetString("BooksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга &quot;{0}&quot;.
        /// </summary>
        public static string BookSent {
            get {
                return ResourceManager.GetString("BookSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книги.
        /// </summary>
        public static string BookSingular {
            get {
                return ResourceManager.GetString("BookSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книги в серии.
        /// </summary>
        public static string BooksInSerie {
            get {
                return ResourceManager.GetString("BooksInSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книги в сериях.
        /// </summary>
        public static string BooksInSeries {
            get {
                return ResourceManager.GetString("BooksInSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        public static string Catalogue {
            get {
                return ResourceManager.GetString("Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цитаты.
        /// </summary>
        public static string Citations {
            get {
                return ResourceManager.GetString("Citations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите.
        /// </summary>
        public static string Come {
            get {
                return ResourceManager.GetString("Come", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string CommentNominative {
            get {
                return ResourceManager.GetString("CommentNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставил(а) комментариев.
        /// </summary>
        public static string CommentsCount {
            get {
                return ResourceManager.GetString("CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментария.
        /// </summary>
        public static string CommentSingular {
            get {
                return ResourceManager.GetString("CommentSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментариев.
        /// </summary>
        public static string CommnetPlural {
            get {
                return ResourceManager.GetString("CommnetPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожаловаться.
        /// </summary>
        public static string Complain {
            get {
                return ResourceManager.GetString("Complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалоба на комментарий.
        /// </summary>
        public static string ComplainEmailSubject {
            get {
                return ResourceManager.GetString("ComplainEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить список устройств.
        /// </summary>
        public static string ConfigureDevices {
            get {
                return ResourceManager.GetString("ConfigureDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;По мере развития нашего ресурса, мы будем постоянно увеличивать количество информации, а также расширять возможности сайта для эффективного удовлетворения Ваших потребностей. Ваше мнение по поводу работы и улучшения сайта очень для нас важно. Пожалуйста, присылайте свои комментарии и пожелания на адрес: &lt;a href=&quot;mailto:{1}&quot;&gt;{1}&lt;/a&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;С уважением, &lt;br/&gt;команда ресурса «{0}»&lt;/p&gt;.
        /// </summary>
        public static string ContactsText {
            get {
                return ResourceManager.GetString("ContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 - {0} &quot;{1}&quot;. Все права защищены.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашли неточность? Исправить!.
        /// </summary>
        public static string CorrectMistakes {
            get {
                return ResourceManager.GetString("CorrectMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обложка.
        /// </summary>
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Составьте свою рецензию.
        /// </summary>
        public static string CreateReview {
            get {
                return ResourceManager.GetString("CreateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный текст отзыва.
        /// </summary>
        public static string CreateReviewFullEmpty {
            get {
                return ResourceManager.GetString("CreateReviewFullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string CreateReviewSubmit {
            get {
                return ResourceManager.GetString("CreateReviewSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to текст отзыва.
        /// </summary>
        public static string CreateReviewSubtitleFull {
            get {
                return ResourceManager.GetString("CreateReviewSubtitleFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оцените книгу.
        /// </summary>
        public static string CreateReviewSubtitleRate {
            get {
                return ResourceManager.GetString("CreateReviewSubtitleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to коротко опишите впечатление о книге.
        /// </summary>
        public static string CreateReviewSubtitleSummary {
            get {
                return ResourceManager.GetString("CreateReviewSubtitleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое впечатление.
        /// </summary>
        public static string CreateReviewSummaryEmpty {
            get {
                return ResourceManager.GetString("CreateReviewSummaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв о книге.
        /// </summary>
        public static string CreateReviewTitle {
            get {
                return ResourceManager.GetString("CreateReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата смерти.
        /// </summary>
        public static string DeathDate {
            get {
                return ResourceManager.GetString("DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалено.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Если Ваше устройство для чтения поддерживает закачку по e-mail, то в этом разделе Вы можете настроить свой список устройств, указав его имя и электронный адрес.&lt;/p&gt;
        ///&lt;p&gt;Для получения книг на устройства Kindle, необходимо на сайте amazon.com добавить транзитный адрес нашего сайта – &lt;a href=&quot;mailto:{0}&quot;&gt;{0}&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Для этого перейдите на страницу &quot;&lt;a target=&quot;_blank&quot; href=&quot;https://www.amazon.com/gp/digital/fiona/manage?ie=UTF8&amp;*Version*=1&amp;*entries*=0&amp;signInRedirect=1&amp;#pdocSettings&quot;&gt;Manage your Kindle&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DevicesInfo {
            get {
                return ResourceManager.GetString("DevicesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;justify&quot;&gt;
        ///        &lt;strong&gt;
        ///            На данном ресурсе не содержится никаких материалов, противоречащих законам какой-либо страны. Все материалы, опубликованные на сайте, перешли в общественное
        ///            достояние. Если Вы заметили нарушение авторских прав, то просим сообщить по адресу
        ///            &lt;a href=&quot;mailto:{0}&quot;&gt;&lt;strong&gt;{0}&lt;/strong&gt;&lt;/a&gt;
        ///        &lt;/strong&gt;
        ///    &lt;/p&gt;
        ///    &lt;p class=&quot;justify&quot;&gt;
        ///        Информационный ресурс &lt;i&gt;knigoskop.com&lt;/i&gt; является общедоступным для пользователей и  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценивать.
        /// </summary>
        public static string DoRate {
            get {
                return ResourceManager.GetString("DoRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлять.
        /// </summary>
        public static string DoSend {
            get {
                return ResourceManager.GetString("DoSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользоваться.
        /// </summary>
        public static string DoUse {
            get {
                return ResourceManager.GetString("DoUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать книгу.
        /// </summary>
        public static string DownloadBook {
            get {
                return ResourceManager.GetString("DownloadBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать файл.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в формате.
        /// </summary>
        public static string DownloadInFormat {
            get {
                return ResourceManager.GetString("DownloadInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать автора.
        /// </summary>
        public static string EditAuthor {
            get {
                return ResourceManager.GetString("EditAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование автора.
        /// </summary>
        public static string EditAuthorTitle {
            get {
                return ResourceManager.GetString("EditAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать книгу.
        /// </summary>
        public static string EditBook {
            get {
                return ResourceManager.GetString("EditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование книги.
        /// </summary>
        public static string EditBookTitle {
            get {
                return ResourceManager.GetString("EditBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить список библиотек.
        /// </summary>
        public static string EditOpdsList {
            get {
                return ResourceManager.GetString("EditOpdsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать рецензию.
        /// </summary>
        public static string EditReview {
            get {
                return ResourceManager.GetString("EditReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование рецензии.
        /// </summary>
        public static string EditReviewTitle {
            get {
                return ResourceManager.GetString("EditReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать серию.
        /// </summary>
        public static string EditSerie {
            get {
                return ResourceManager.GetString("EditSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование серии.
        /// </summary>
        public static string EditSerieTitle {
            get {
                return ResourceManager.GetString("EditSerieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmailShort {
            get {
                return ResourceManager.GetString("EmailShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; обязательно к заполнению.
        /// </summary>
        public static string FieldRequiredMessage {
            get {
                return ResourceManager.GetString("FieldRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат адреса электронной почты.
        /// </summary>
        public static string FieldWrongEmailMessage {
            get {
                return ResourceManager.GetString("FieldWrongEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти книгу.
        /// </summary>
        public static string FindBook {
            get {
                return ResourceManager.GetString("FindBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти книгу в Google.
        /// </summary>
        public static string FindBookInGoogle {
            get {
                return ResourceManager.GetString("FindBookInGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и получите возможность.
        /// </summary>
        public static string GetPossibility {
            get {
                return ResourceManager.GetString("GetPossibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вверх.
        /// </summary>
        public static string GoTop {
            get {
                return ResourceManager.GetString("GoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Вы часто задаете себе вопрос, что прочитать еще? Вы под впечатлением от нового автора и хотите продолжить знакомство с его творчеством? Вас тронула тема вновь прочитанной книги и Вы хотите погрузиться в тему еще глубже?&lt;/p&gt;
        ///
        ///&lt;p&gt;Мы не только предоставляем доступ к широчайшему каталогу литературы с аннотациями, но и даем удобный инструмент поиска произведений схожей тематики.&lt;/p&gt;
        ///
        ///&lt;p&gt;Интеллектуальный поиск покажет Вам перечень похожих произведений.&lt;/p&gt;
        ///
        ///&lt;p&gt;Вы никогда не останетесь без интересной и ув [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступления.
        /// </summary>
        public static string Incomes {
            get {
                return ResourceManager.GetString("Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши исправления сохранены и будут размещены на сайте после рассмотрения модератором.
        /// </summary>
        public static string IncomeUpdated {
            get {
                return ResourceManager.GetString("IncomeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как это работает?.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат Email.
        /// </summary>
        public static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный адреса OPDS.
        /// </summary>
        public static string InvalidOPDSUrlMessage {
            get {
                return ResourceManager.GetString("InvalidOPDSUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат адреса.
        /// </summary>
        public static string InvalidUrlMessage {
            get {
                return ResourceManager.GetString("InvalidUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читаю.
        /// </summary>
        public static string IsReading {
            get {
                return ResourceManager.GetString("IsReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставьте свой коментарий.
        /// </summary>
        public static string LeaveTheComment {
            get {
                return ResourceManager.GetString("LeaveTheComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет загрузка. Пожалуйста подождите....
        /// </summary>
        public static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии, дискуссии, книжная полка, отзывы и рекомендации и многое другое после регистрации.
        /// </summary>
        public static string LoginHint {
            get {
                return ResourceManager.GetString("LoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название книги или имя автора.
        /// </summary>
        public static string MainSearchPlaceHolder {
            get {
                return ResourceManager.GetString("MainSearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше книг.
        /// </summary>
        public static string MoreBooks {
            get {
                return ResourceManager.GetString("MoreBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои книги.
        /// </summary>
        public static string MyBookmarks {
            get {
                return ResourceManager.GetString("MyBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои устройства.
        /// </summary>
        public static string MyDevices {
            get {
                return ResourceManager.GetString("MyDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои вещи.
        /// </summary>
        public static string MyThings {
            get {
                return ResourceManager.GetString("MyThings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новинки.
        /// </summary>
        public static string NewBooks {
            get {
                return ResourceManager.GetString("NewBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое поступление.
        /// </summary>
        public static string NewIncomeEmailSubject {
            get {
                return ResourceManager.GetString("NewIncomeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть новые поступления.
        /// </summary>
        public static string NewIncomes {
            get {
                return ResourceManager.GetString("NewIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать рецензию.
        /// </summary>
        public static string NewReview {
            get {
                return ResourceManager.GetString("NewReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свежие рецензии.
        /// </summary>
        public static string NewReviews {
            get {
                return ResourceManager.GetString("NewReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здесь пока ничего нет....
        /// </summary>
        public static string NothingThere {
            get {
                return ResourceManager.GetString("NothingThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получать нотификации.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одноклассники.
        /// </summary>
        public static string Odnoklassniki {
            get {
                return ResourceManager.GetString("Odnoklassniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.onlini.co.
        /// </summary>
        public static string Onlinico {
            get {
                return ResourceManager.GetString("Onlinico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здесь Вы можете добавить ссылки на собственные OPDS каталоги, что позволит находить книги непосредственно в любимых Вами библиотеках..
        /// </summary>
        public static string OpdsInfo {
            get {
                return ResourceManager.GetString("OpdsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что такое OPDS?.
        /// </summary>
        public static string OpdsInfoRef {
            get {
                return ResourceManager.GetString("OpdsInfoRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотеки.
        /// </summary>
        public static string OpdsSettings {
            get {
                return ResourceManager.GetString("OpdsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opds источник.
        /// </summary>
        public static string OpdsSource {
            get {
                return ResourceManager.GetString("OpdsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя источника.
        /// </summary>
        public static string OpdsSourceName {
            get {
                return ResourceManager.GetString("OpdsSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес источника.
        /// </summary>
        public static string OpdsSourceUrl {
            get {
                return ResourceManager.GetString("OpdsSourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши контакты.
        /// </summary>
        public static string OurContacts {
            get {
                return ResourceManager.GetString("OurContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страниц.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество страниц.
        /// </summary>
        public static string PagesCount {
            get {
                return ResourceManager.GetString("PagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to страница.
        /// </summary>
        public static string PagesNominative {
            get {
                return ResourceManager.GetString("PagesNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to страниц.
        /// </summary>
        public static string PagesPlural {
            get {
                return ResourceManager.GetString("PagesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to страницы.
        /// </summary>
        public static string PagesSingular {
            get {
                return ResourceManager.GetString("PagesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной адрес.
        /// </summary>
        public static string PrimaryEmail {
            get {
                return ResourceManager.GetString("PrimaryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработать запись?.
        /// </summary>
        public static string ProcessIncomeConfirm {
            get {
                return ResourceManager.GetString("ProcessIncomeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрирован.
        /// </summary>
        public static string ProfileCreated {
            get {
                return ResourceManager.GetString("ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки профиля.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книжный рекомендательный сервис.
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книгоскоп.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читай больше хороших книг.
        /// </summary>
        public static string PromoText {
            get {
                return ResourceManager.GetString("PromoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцените книгу.
        /// </summary>
        public static string RateBook {
            get {
                return ResourceManager.GetString("RateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставил(а) оценок.
        /// </summary>
        public static string RatingsCount {
            get {
                return ResourceManager.GetString("RatingsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочел.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть.
        /// </summary>
        public static string ReadLess {
            get {
                return ResourceManager.GetString("ReadLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать полностью.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить книгу.
        /// </summary>
        public static string ReceiveBook {
            get {
                return ResourceManager.GetString("ReceiveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выхода.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить комментарий.
        /// </summary>
        public static string RemoveComment {
            get {
                return ResourceManager.GetString("RemoveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить запись?.
        /// </summary>
        public static string RemoveIncomeConfirm {
            get {
                return ResourceManager.GetString("RemoveIncomeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожаловаться на комментарий.
        /// </summary>
        public static string ReportComment {
            get {
                return ResourceManager.GetString("ReportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожаловаться.
        /// </summary>
        public static string ReportCommentButton {
            get {
                return ResourceManager.GetString("ReportCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коротко опишите причину жалобы.
        /// </summary>
        public static string ReportCommentEmptyText {
            get {
                return ResourceManager.GetString("ReportCommentEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to опишите причину.
        /// </summary>
        public static string ReportCommentSubtitle {
            get {
                return ResourceManager.GetString("ReportCommentSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жалоба на комментарий.
        /// </summary>
        public static string ReportCommentTitle {
            get {
                return ResourceManager.GetString("ReportCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга должна иметь автора (-ов).
        /// </summary>
        public static string RequiredAuthorMessage {
            get {
                return ResourceManager.GetString("RequiredAuthorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это поле не может быть пустым.
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга должна относится к жанру (-ам).
        /// </summary>
        public static string RequiredGenreMessage {
            get {
                return ResourceManager.GetString("RequiredGenreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже составили рецензию на эту книгу.
        /// </summary>
        public static string ReviewAlreadyExists {
            get {
                return ResourceManager.GetString("ReviewAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст рецензии.
        /// </summary>
        public static string ReviewDescription {
            get {
                return ResourceManager.GetString("ReviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое впечатление.
        /// </summary>
        public static string ReviewName {
            get {
                return ResourceManager.GetString("ReviewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рецензия на книгу.
        /// </summary>
        public static string ReviewOnBook {
            get {
                return ResourceManager.GetString("ReviewOnBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша оценка книги.
        /// </summary>
        public static string ReviewRating {
            get {
                return ResourceManager.GetString("ReviewRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рецензии.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написал(а) рецензий.
        /// </summary>
        public static string ReviewsCount {
            get {
                return ResourceManager.GetString("ReviewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста заполните все поля - рейтинг, краткий и полный отзыв.
        /// </summary>
        public static string ReviewValidation {
            get {
                return ResourceManager.GetString("ReviewValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск книги или автора.
        /// </summary>
        public static string SearchBookOrAuthor {
            get {
                return ResourceManager.GetString("SearchBookOrAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искать!.
        /// </summary>
        public static string SearchButtonHint {
            get {
                return ResourceManager.GetString("SearchButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серии.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название серии.
        /// </summary>
        public static string SeriesName {
            get {
                return ResourceManager.GetString("SeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще!...
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похожие книги.
        /// </summary>
        public static string SimilarBooks {
            get {
                return ResourceManager.GetString("SimilarBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найди много хороших книг.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти через социальные сети.
        /// </summary>
        public static string SocialAuth {
            get {
                return ResourceManager.GetString("SocialAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правообладателям.
        /// </summary>
        public static string ToCopyrightHolders {
            get {
                return ResourceManager.GetString("ToCopyrightHolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перевод.
        /// </summary>
        public static string TranslatedBy {
            get {
                return ResourceManager.GetString("TranslatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставлять комментарии могут только авторизированные пользователи..
        /// </summary>
        public static string UnauthorizedComments {
            get {
                return ResourceManager.GetString("UnauthorizedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Составлять рецензии могут только авторизированные пользователи..
        /// </summary>
        public static string UnauthorizedReviews {
            get {
                return ResourceManager.GetString("UnauthorizedReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опс! Возникла ошибка при обработке Вашего запроса. Повторите попытку позже..
        /// </summary>
        public static string UnknownErrorOccured {
            get {
                return ResourceManager.GetString("UnknownErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to закладками.
        /// </summary>
        public static string UseBookmarks {
            get {
                return ResourceManager.GetString("UseBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to книги и авторов.
        /// </summary>
        public static string UseBooksAndAuthors {
            get {
                return ResourceManager.GetString("UseBooksAndAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to комментарии и рекоммендации.
        /// </summary>
        public static string UseComments {
            get {
                return ResourceManager.GetString("UseComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о пользователе.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотров за месяц.
        /// </summary>
        public static string ViewsMonth {
            get {
                return ResourceManager.GetString("ViewsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотров сегодня.
        /// </summary>
        public static string ViewsToday {
            get {
                return ResourceManager.GetString("ViewsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотров за все время.
        /// </summary>
        public static string ViewsTotal {
            get {
                return ResourceManager.GetString("ViewsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотров за неделю.
        /// </summary>
        public static string ViewsWeek {
            get {
                return ResourceManager.GetString("ViewsWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотров за год.
        /// </summary>
        public static string ViewsYear {
            get {
                return ResourceManager.GetString("ViewsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВКонтакте.
        /// </summary>
        public static string Vkontakte {
            get {
                return ResourceManager.GetString("Vkontakte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to голос.
        /// </summary>
        public static string VoteNominative {
            get {
                return ResourceManager.GetString("VoteNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to голосов.
        /// </summary>
        public static string VotePlural {
            get {
                return ResourceManager.GetString("VotePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to голоса.
        /// </summary>
        public static string VoteSingular {
            get {
                return ResourceManager.GetString("VoteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу прочесть.
        /// </summary>
        public static string WantsToRead {
            get {
                return ResourceManager.GetString("WantsToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание метаданных вебсервиса.
        /// </summary>
        public static string WebApiDocumentation {
            get {
                return ResourceManager.GetString("WebApiDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia.
        /// </summary>
        public static string Wikipedia {
            get {
                return ResourceManager.GetString("Wikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите комментарий.
        /// </summary>
        public static string WriteComment {
            get {
                return ResourceManager.GetString("WriteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорhектный формат изображения.
        /// </summary>
        public static string WrongImageFormat {
            get {
                return ResourceManager.GetString("WrongImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яндекс.
        /// </summary>
        public static string Yandex {
            get {
                return ResourceManager.GetString("Yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
